# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labfolder_license_checker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='active_users_last_6_months',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
